- include_role:
    name: software_install
    tasks_from: core

- name: "Create virtualenv venv"
  command: "{{ software_path }}/apps/python_3/{{ python_version }}/bin/python3 -m venv {{ install_path }}"

- name: "Install virtualenv package"
  pip:
    executable: "{{ install_path }}/bin/pip"
    name: virtualenv
