---
- include_role:
    name: software_install
  vars:
    steps:
      - setup_venv
    name: "virtualenv"

    description: "virtualenv is a tool to create isolated Python environments."
    website: "https://virtualenv.pypa.io/en/latest"
    testing: "virtualenv"
    depends_on:
      - python_3
