---
- include_role:
    name: go
  vars:
    go_version: "1.20.6"

- include_role:
    name: software_install
  vars:
    apptainer_source: "https://github.com/apptainer/apptainer/releases/download/v1.3.1/apptainer-1.3.1.tar.gz"
