---
name: "perl"
perl_steps:
  - download
  - extract
  - build
perl_default_version: "5.36.0"
perl_build_configure_cmd: "./Configure -des -Dprefix={{ perl_install_path }} -Dusethreads"

perl_description: "Perl is a family of two high-level, general purpose, interpreted, dynamic programming languages."
perl_testing_cmd: "perl -v"
perl_website: "https://www.perl.org"
