---
name: "fuse"
fuse_steps:
  - download
  - extract
  - build
fuse_default_version: "3.17.4"
fuse_build_system: "meson"

fuse_description: "The reference implementation of the Linux FUSE (Filesystem in Userspace) interface"
fuse_website: "https://github.com/libfuse/libfuse"
fuse_testing_cmd: "fusermount3 --help"
