---
name: "mpc"
mpc_default_version: "1.3.1"
mpc_steps:
  - download
  - extract
  - build
mpc_build_configure_flags: "--with-mpfr={{ mpfr_install_path }}"

mpc_description: "GNU MPC is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result."
mpc_website: "https://www.multiprecision.org"
