---
name: "sparsehash"
sparsehash_steps:
  - download
  - extract
  - build
sparsehash_default_version: "2.0.4"

sparsehash_description: "sparsehash is an extremely memory-efficient hash map implementation."
sparsehash_website: "https://goog-sparsehash.sourceforge.net"
