---
- include_role:
    name: software_dependencies
  loop:
    - { name: gmp, version: "6.2.1" }
    - { name: mpfr, version: "4.2.0" }
    - { name: mpc, version: "1.3.1" }
  loop_control:
    loop_var: gcc_dependencies

- include_role:
    name: software_install
  vars:
    gcc_source: "https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz"
