---
- include_role:
    name: gmp
  vars:
    gmp_version: "6.2.1"

- include_role:
    name: mpfr
  vars:
    mpfr_version: "4.2.0"

- include_role:
    name: mpc
  vars:
    mpc_version: "1.3.1"

- include_role:
    name: go
  vars:
    go_version: "1.20.6"

- include_role:
    name: software_install
  vars:
    gcc_source: "https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz"
