name: "libexpat"
libexpat_steps:
  - download_software
  - extract_software
  - build_software
libexpat_version: "2.7.3"
libexpat_file: "expat-{{ libexpat_version }}.tar.gz"
libexpat_source: "https://github.com/libexpat/libexpat/releases/download/R_2_7_3/{{ libexpat_file }}"

libexpat_description: "Expat is a stream-oriented parser in which an application registers handlers for things the parser might find in the XML document (like start tags)."
libexpat_website: "https://libexpat.github.io"
libexpat_testing: "xmlwf --help"
