---
name: "glib_2"
glib_2_steps:
  - download_software
  - extract_software
  - build_software
glib_2_version: "2.87.0"
glib_2_file: "glib-{{ glib_2_version }}.tar.xz"
glib_2_source: "https://download.gnome.org/sources/glib/2.87/{{ glib_2_file }}"
glib_2_build_system: "meson"
glib_2_build_env:
  PKG_CONFIG_PATH: "{{ pcre2_install_path }}/lib/pkgconfig"
glib_2_build_configure_cmd: "{{ meson_install_path }}/bin/meson setup build --prefix={{ glib_2_install_path }}"

glib_2_description: "GLib is a general-purpose, portable utility library, which provides many useful data types, macros, type conversions, string utilities, file utilities, a mainloop abstraction, and so on."
glib_2_website: "https://www.gtk.org"
