---
name: "tcl"
tcl_steps:
  - download_software
  - extract_software
  - build_software
tcl_version: "8.6.13"
tcl_file: "tcl8613-src.zip"
tcl_source: "http://prdownloads.sourceforge.net/tcl/{{ tcl_file }}"
tcl_build_dir: "{{ tcl_build_path }}/tcl{{ tcl_version }}/unix"
tcl_build_configure_flags: "--enable-threads"

tcl_description: "Tcl (Tool Command Language) is a very powerful but easy to learn dynamic programming language, suitable for a very wide range of uses, including web and desktop applications, networking, administration, testing and many more."
tcl_website: "https://www.tcl-lang.org"
