---
name: "libfuse"
libfuse_steps:
  - download_software
  - extract_software
  - build_software
libfuse_version: "3.17.4"
libfuse_file: "fuse-{{ libfuse_version }}.tar.gz"
libfuse_source: "https://github.com/libfuse/libfuse/releases/download/fuse-{{ libfuse_version }}/{{ libfuse_file }}"
libfuse_build_system: "meson"

libfuse_description: "The reference implementation of the Linux FUSE (Filesystem in Userspace) interface"
libfuse_website: "https://github.com/libfuse/libfuse"
