---
name: "pcre2"
pcre2_steps:
  - download_software
  - extract_software
  - build_software
pcre2_version: "10.47"
pcre2_file: "pcre2-{{ pcre2_version }}.tar.gz"
pcre2_source: "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-{{ pcre2_version }}/{{ pcre2_file }}"

pcre2_website: "https://pcre2project.github.io/pcre2"
pcre2_description: "The PCRE2 library is a set of C functions that implement regular expression pattern matching."
