---
name: "pcre2"
pcre2_steps:
  - download
  - extract
  - build
pcre2_default_version: "10.47"

pcre2_website: "https://pcre2project.github.io/pcre2"
pcre2_description: "The PCRE2 library is a set of C functions that implement regular expression pattern matching."
pcre2_testing_cmd: "pcre2test -help"
