---
- include_role:
    name: expat
  vars:
    expat_version: "2.7.3"

- include_role:
    name: software_install
  vars:
    udunits_source: "https://downloads.unidata.ucar.edu/udunits/2.2.28/udunits-2.2.28.tar.gz"
