---
- include_role:
    name: software_install
  vars:
    steps:
      - download_software
      - extract_software
      - build_software
    name: "texinfo"
    version: "7.0"
    file: "texinfo-{{ version }}.tar.gz"
    source: "https://ftp.gnu.org/gnu/texinfo/{{ file }}"
    build_env:
      PATH: "{{ software_info.perl.install_path }}/bin:{{ ansible_env.PATH }}"

    description: "Texinfo uses a single source file to produce output in a number of formats, both online and printed (HTML, PDF, DVI, Info, DocBook, LaTeX, EPUB 3). This means that instead of writing different documents for online information and another for a printed manual, you need write only one document. The Texinfo system is well-integrated with GNU Emacs."
    website: "https://www.gnu.org/software/texinfo"
    testing: "info -h"
