---
name: "node"
node_default_version: "24.12.0"
node_steps:
  - download
  - extract
  - install_prebuilt

node_website: "https://github.com/nodejs/node"
node_description: "Node.js JavaScript runtime âœ¨ğŸ¢ğŸš€âœ¨"
