---
name: "gperf"
gperf_steps:
  - download_software
  - extract_software
  - build_software
gperf_version: "3.3"
gperf_file: "gperf-{{ gperf_version }}.tar.gz"
gperf_source: "http://ftp.gnu.org/pub/gnu/gperf/{{ gperf_file }}"

gperf_description: " GNU gperf is a perfect hash function generator. For a given list of strings, it produces a hash function and hash table, in form of C or C++ code, for looking up a value depending on the input string. The hash function is perfect, which means that the hash table has no collisions, and the hash table lookup needs a single string comparison only."
gperf_website: "https://www.gnu.org/software/gperf"
gperf_testing_cmd: "gperf --help"
