- include_role:
    name: software_install
  vars:
    steps:
      - download_software
      - extract_software
      - build_software
    name: "pcre2"
    version: "10.47"
    file: "pcre2-{{ version }}.tar.gz"
    source: "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-{{ version }}/{{ file }}"

    website: "https://pcre2project.github.io/pcre2"
    description: "The PCRE2 library is a set of C functions that implement regular expression pattern matching."
