---
- include_role:
    name: meson

- include_role:
    name: pcre2

- include_role:
    name: software_install
  vars:
    glib_source: "https://download.gnome.org/sources/glib/2.87/glib-2.87.0.tar.xz"
