---
name: "swig"
swig_steps:
  - download_software
  - extract_software
  - build_software
swig_version: "4.1.1"
swig_file: "swig-{{ swig_version }}.tar.gz"
swig_source: "https://sourceforge.net/projects/swig/files/swig/swig-{{ swig_version }}/{{ swig_file }}"
swig_build_env:
  PATH: "{{ pcre2_install_path }}/bin:{{ ansible_env.PATH }}"

swig_description: "SWIG is an interface compiler that connects programs written in C and C++ with scripting languages such as Perl, Python, Ruby, and Tcl"
swig_testing: "swig --help"
swig_website: "https://www.swig.org"
swig_depends_on:
  - pcre2
