---
- include_role:
    name: gperf

- include_role:
    name: software_install
  vars:
    libseccomp_version: "2.6.0"
    libseccomp_source: "https://github.com/seccomp/libseccomp/releases/download/v2.6.0/libseccomp-2.6.0.tar.gz"
