---
name: "zlib"
zlib_steps:
  - download_software
  - extract_software
  - build_software
zlib_version: "1.3.1"
zlib_file: "zlib-{{ zlib_version }}.tar.gz"
zlib_source: "https://zlib.net/{{ zlib_file }}"

zlib_description: |
  zlib is a free, general purpose lossless compression library for use on virtually any computer hardware and OS.
  zlib is a compression platform that is portable across platforms.
zlib_website: "https://zlib.net"
