---
name: "zlib"
zlib_steps:
  - download
  - extract
  - build
zlib_default_version: "1.3.1"

zlib_description: |
  zlib is a free, general purpose lossless compression library for use on virtually any computer hardware and OS.
  zlib is a compression platform that is portable across platforms.
zlib_website: "https://zlib.net"
