---
name: "go"
go_steps:
  - download_software
  - extract_software
  - install_prebuilt
go_default_version: "1.20.6"
go_version: "{{ go_default_version }}"

go_description: "go is an open-source programming language supported by Google"
go_testing_cmd: "go version"
go_website: "https://go.dev/doc"
