---
name: "go"
go_steps:
  - download
  - extract
  - install_prebuilt
go_default_version: "1.20.6"

go_description: "go is an open-source programming language supported by Google"
go_testing_cmd: "go version"
go_website: "https://go.dev/doc"
