- include_role:
    name: software_install
  vars:
    steps:
      - download_software
      - extract_software
      - build_software
    name: "swig"
    version: "4.1.1"
    file: "swig-{{ version }}.tar.gz"
    source: "https://sourceforge.net/projects/swig/files/swig/swig-{{ version }}/{{ file }}"
    build_env:
      PATH: "{{ software_info.pcre2.install_path }}/bin:{{ ansible_env.PATH }}"

    description: "SWIG is an interface compiler that connects programs written in C and C++ with scripting languages such as Perl, Python, Ruby, and Tcl"
    testing: "swig --help"
    website: "https://www.swig.org"
    depends_on:
      - pcre2
