---
name: "singularityCE"
singularityCE_steps:
  - download
  - extract
  - build
singularityCE_default_version: "3.11.4"
singularityCE_build_env:
  PATH: "{{ go_install_path }}/bin:{{ ansible_env.PATH }}"
  CFLAGS: "-I{{ libseccomp_install_path }}/include"
  LDFLAGS: "-L{{ libseccomp_install_path }}/lib"
  PKG_CONFIG_PATH: "{{ libseccomp_install_path }}/lib/pkgconfig:{{ pcre2_install_path }}/lib/pkgconfig"
singularityCE_build_configure_cmd: "./mconfig --prefix={{ singularityCE_install_path }} --localstatedir=/var --sysconfdir={{ singularityCE_install_path }}/etc"
singularityCE_build_make_flags: "-C ./builddir"
singularityCE_build_install_flags: "-C ./builddir"

singularityCE_description: "singularityCE enables users to have full control of their operating system environment. This means that a non-privileged user can “swap out” the operating system on the host for one they control. So if the host system is running RHEL6 but your application runs in Ubuntu, you can create an Ubuntu image, install your applications into that image, copy the image to another host, and run your application on that host in it’s native Ubuntu environment!"
singularityCE_website: "https://docs.sylabs.io/guides/latest/user-guide"
singularityCE_testing_cmd: "singularity --help"
