---
name: "ruby"
ruby_default_version: "3.2.1"
ruby_steps:
  - download
  - extract
  - build

ruby_website: "https://www.ruby-lang.org/en"
ruby_description: "A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write."
ruby_testing_cmd: "ruby -v"
