---
name: "python"
python_steps:
  - download
  - extract
  - build
python_default_version: "3.9.18"
python_build_configure_flags: "--with-pydebug --with-ensurepip=install"

python_description: "Python is an interpreted, object-oriented, high-level programming language."
python_testing_cmd: "python -V"
python_website: "https://python.org"

python_conflicts:
  - miniconda
