---
name: "tk"
tk_steps:
  - download_software
  - extract_software
  - build_software
tk_version: "8.6.13"
tk_file: "tk8613-src.zip"
tk_source: "http://prdownloads.sourceforge.net/tcl/{{ tk_file }}"
tk_build_dir: "{{ tk_build_path }}/tk{{ tk_version }}/unix"
tk_build_configure_flags: "--enable-threads --with-tcl={{ tcl_install_path }}/lib"

tk_description: " Tk is a graphical user interface toolkit that takes developing desktop applications to a higher level than conventional approaches. Tk is the standard GUI not only for Tcl, but for many other dynamic languages, and can produce rich, native applications that run unchanged across Windows, Mac OS X, Linux and more."
tk_website: "https://www.tcl-lang.org"
