---
name: "wget"
wget_steps:
  - download_software
  - extract_software
  - build_software
wget_default_version: "1.21.3"
wget_version: "{{ wget_default_version }}"

wget_description: "GNU Wget is a free software package for retrieving files using HTTP, HTTPS, FTP and FTPS, the most widely used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc."
wget_website: "https://www.gnu.org/software/wget"
wget_testing_cmd: "wget --help"
