---
name: "sqlite_3"
sqlite_3_steps:
  - download_software
  - extract_software
  - build_software
sqlite_3_version: "3.40.1"
sqlite_3_file: "version-{{ sqlite_3_version }}.tar.gz"
sqlite_3_source: "https://github.com/sqlite/sqlite/archive/refs/tags/{{ sqlite_3_file }}"

sqlite_3_description: "sqlite3 is a C library that provides a lightweight disk-based database that doesn't require a separate server process and allows accessing the database using a nonstandard variant of SQL query language."
sqlite_3_website: "https://sqlite.org"
sqlite_3_testing_cmd: "sqlite3 --help"
