---
name: "nvim"
nvim_default_version: "0.11.5"
nvim_steps:
  - download
  - extract
  - install_prebuilt

nvim_website: "https://neovim.io"
nvim_description: "Vim-fork focused on extensibility and usability"
