---
- include_role:
    name: fuse
  vars:
    fuse_version: "3.17.4"

- include_role:
    name: software_install
  vars:
    squashfuse_source: "https://github.com/vasi/squashfuse/releases/download/0.5.2/squashfuse-0.5.2.tar.gz"
