---
name: "gcc"
gcc_default_version: "12.2.0"
gcc_steps:
  - download
  - extract
  - build
gcc_build_configure_flags: "--enable-languages=c,c++,fortran,go --disable-multilib --with-gmp={{ gmp_install_path }} --with-mpfr={{ mpfr_install_path }} --with-mpc={{ mpc_install_path }}"
gcc_build_env:
  PATH: "{{ go_install_path }}/bin:{{ ansible_env.PATH }}"
  GOROOT: "{{ go_install_path }}"

gcc_website: "https://gcc.gnu.org"
gcc_description: "The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, D, Modula-2, and COBOL as well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom."
