- include_role:
    name: software_install
  vars:
    steps:
      - setup_venv
    name: "meson"

    testing: "meson"
    libraries_used: "python3"
    depends_on:
      - python_3
    packages_used: "python3"
