---
name: "xz"
xz_steps:
  - download
  - extract
  - build
xz_default_version: "5.4.1"

xz_description: |
  xz is a general-purpose, command line data compression utility, similar to gzip and bzip2.
  xz can be used to compress or decompress a file according to the selected operation mode.
xz_website: "https://tukaani.org/xz"
xz_testing_cmd: "xz --help"
