---
name: "virtualenv"
virtualenv_steps:
  - create_venv

virtualenv_description: "virtualenv is a tool to create isolated Python environments."
virtualenv_website: "https://virtualenv.pypa.io/en/latest"
virtualenv_testing_cmd: "virtualenv"
